name: Sync fork
on: repository_dispatch
jobs:
  sync_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: fetch
        run: |
          git remote add upstream https://github.com/ElpsyCN/el-bot-api.git
          git fetch upstream
          git merge upstream/master
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
